---

- name: ensure tasks run only on selected os releases
  block:

    - name: update installed packages
      ansible.builtin.package:
        name: "*"
        state: latest
      ignore_errors: true

    - name: install additional packages
      ansible.builtin.package:
        name: "{{ baseline_packages }}"
        state: present

    - name: display grub menu
      ansible.builtin.include_role:
        name: boot_loader
        tasks_from: grub_settings.yml
      vars:
        grub_settings:
          - key: GRUB_HIDDEN_TIMEOUT
            value: 0
          - key: GRUB_TIMEOUT_STYLE
            value: menu
          - key: GRUB_TIMEOUT
            value: 5

    - name: remove default kernel arguments
      ansible.builtin.include_role:
        name: boot_loader
        tasks_from: kernel_arguments.yml
      vars:
        grubby_task: remove
        kernel_arguments:
          - crashkernel
          - quiet
          - rhgb

    - name: deploy cockpit
      ansible.builtin.include_role:
        name: remote_management
        tasks_from: cockpit_deploy.yml

    - name: deploy chrony
      ansible.builtin.include_role:
        name: time_synchronization
        tasks_from: chrony_deploy.yml

    - name: deploy fastfetch
      ansible.builtin.include_role:
        name: system_information
        tasks_from: fastfetch_deploy.yml

    - name: "disable services {{ disabled_services }}"
      ansible.builtin.command:
        cmd: "systemctl disable --now {{ disabled_services | join(' ') }}"
      register: services_disabled
      failed_when:
        - services_disabled is failed
        - "'does not exist' not in services_disabled.stderr"
        - "'not loaded' not in services_disabled.stderr"

    - name: display disabled services
      ansible.builtin.debug:
        var: services_disabled
        verbosity: 1

  when: ansible_distribution == "Fedora"

...
