---

- name: ensure tasks run only on selected os releases
  block:

    - name: check for battery charging threshold support - option 1
      ansible.builtin.find:
        path: /sys/class/power_supply
        patterns: "charge_control_*_threshold"
        file_type: file
        depth: 2
        follow: true
        recurse: true
      register: battery_threshold_1

    - name: display battery threshold support - option 1
      ansible.builtin.debug:
        var: battery_threshold_1
        verbosity: 1

    - name: check for battery charging threshold support - option 2
      ansible.builtin.find:
        path: /sys/class/hwmon
        patterns: max_battery_charge_level
        file_type: file
        depth: 2
        follow: true
        recurse: true
      register: battery_threshold_2

    - name: display battery threshold support - option 2
      ansible.builtin.debug:
        var: battery_threshold_2
        verbosity: 1

    - name: enable battery threshold customizations - option 1
      block:

        - name: enable battery threshold customizations - option 1
          ansible.builtin.shell:
            cmd: "echo {{ min_charge_threshold }} > {{ item.path }}"
          when: "'_start_' in item.path"
          loop: "{{ battery_threshold_1.files }}"
          loop_control:
            label: "{{ item.path }}"

        - name: enable battery threshold customizations - option 1
          ansible.builtin.shell:
            cmd: "echo {{ max_charge_threshold }} > {{ item.path }}"
          when: "'_end_' in item.path"
          loop: "{{ battery_threshold_1.files }}"
          loop_control:
            label: "{{ item.path }}"

      when:
        - battery_threshold_1.matched > 0
        - min_charge_threshold is defined
        - max_charge_threshold is defined

    - name: enable battery threshold customizations - option 2
      block:

        - name: enable battery threshold customizations - option 2
          ansible.builtin.shell:
            cmd: "echo {{ max_charge_threshold }} > {{ item.path }}"
          loop: "{{ battery_threshold_2.files }}"
          loop_control:
            label: "{{ item.path }}"

      when:
        - battery_threshold_2.matched > 0
        - min_charge_threshold is defined
        - max_charge_threshold is defined

  when: >
    os_id.stdout == "bazzite" or
    os_id.stdout == "fedora" or
    os_id.stdout == "rhel" or
    os_id.stdout == "rocky" or
    os_id.stdout == "steamos"
