---

- name: ensure tasks run only on selected os releases
  block:

    - name: update installed packages
      ansible.builtin.package:
        name: "*"
        state: latest
      ignore_errors: true

    - name: install additional packages
      ansible.builtin.package:
        name: "{{ baseline_packages }}"
        state: present

    - name: display grub menu
      ansible.builtin.include_role:
        name: boot_loader
        tasks_from: grub_settings.yml
      vars:
        grub_settings:
          - key: GRUB_HIDDEN_TIMEOUT
            value: 0
          - key: GRUB_TIMEOUT_STYLE
            value: menu
          - key: GRUB_TIMEOUT
            value: 5

    - name: remove default kernel arguments
      ansible.builtin.include_role:
        name: boot_loader
        tasks_from: kernel_arguments.yml
      vars:
        grubby_task: remove
        kernel_arguments:
          - crashkernel
          - quiet
          - rhgb

    - name: execute handlers
      meta: flush_handlers

    - name: reboot system if required
      block:

      - name: check if a reboot is required
        ansible.builtin.command:
          cmd: dnf needs-restarting -r
        changed_when: reboot_needed.rc != 0
        failed_when: false
        notify: initiate reboot
        register: reboot_needed

      - name: display reboot flag
        ansible.builtin.debug:
          var: reboot_needed
          verbosity: 1

      when:
        - reboot is defined
        - reboot

  when: ansible_distribution == "Fedora"

...
